// subbar
export default [
  // {
  //   name: 'deviceInvolved',
  //   text: '已接入',
  //   showList: ['id','name','sn', 'roadCount','address','addressType','online', 'doorOpened','category','supplyer','createdAt'],
  //   api: 'admin/device/involved',
  // },
  // {
  //   name: 'deviceUnInvolved',
  //   text: '未接入',
  //   showList: ['id','articleName', 'authorName','authorUserId','likes','status','amount', 'createTime',],
  //   api: 'manage/getArtcle',
  // },
  // {
  //   name: 'classifyList',
  //   text: '商品分类',
  //   icon: '&#xe651;',
  //   showList: ['id','goodsClassName','status', 'createTime','goodsClassModels'],
  //   api: 'manage/goods/classList',
  //   addUrl: 'classify',
    
  // },
  // {
  //   name: 'wareList',
  //   text: '商品列表',
  //   icon: '&#xe6ca;',
  //   showList: ['id','goodsName','goodsClassName','goodsPhoto', 'classId','price','sale','stock','discount','level','top','createTime'],
  //   api: 'manage/goods/goodsList',
  //   addUrl: 'Goods',
    
  // },
  // {
  //   name: 'cardList',
  //   text: '优惠券',
  //   icon: '&#xe627;',
  //   showList: ['id','cardName','cardMoney','cardDetails', 'cardNum','cardOutTime','type','useCardNum','createTime'],
  //   api: 'manage/card/cardList',
  //   addUrl: 'card',
  // },
  // {
  //   name: 'cardBindList',
  //   text: '已领优惠券',
  //   icon: '&#xe658;',
  //   showList: ['id','cardName','cardMoney','cardDetails','type', 'userId','isRead','createTime','endTime'],
  //   api: 'manage/card/cardBindList',
  //   addUrl: 'card',
  // },
  // {
  //   name: 'levelList',
  //   text: '用户等级',
  //   icon: '&#xe61b;',
  //   showList: ['id','levelName', 'levelDiscount','levelDeposit','levelNum'],
  //   api: 'manage/user/levelList',
  //   addUrl: '',
  // },
  // {
  //   name: 'shufflingList',
  //   text: '轮播列表',
  //   icon: '&#xe608;',
  //   showList: ['id','img','title','note', 'status','detailsId','url','type'],
  //   api: 'manage/getShufflingAll',
  //   addUrl: 'Shuffling',
  // },
  // {
  //   name: 'orderList',
  //   text: '订单列表',
  //   icon: '&#xe605;',
  //   showList: ['userId','goodsList','afford', 'payType','type','elseOrderId','createTime','addressID','orderId'],
  //   api: 'manage/order/orderList',
  //   // addUrl: 'Shuffling',
  // },
  // {
  //   name: 'orderCustomerList',
  //   text: '投诉列表',
  //   icon: '&#xe666;',
  //   showList: ['id','userId','complaint','note', 'adminId','type','createTime','orderId'],
  //   api: 'manage/order/orderCustomerList',
  //   // addUrl: 'Shuffling',
  // },
  // {
  //   name: 'dateInfoList',
  //   text: '金额记录',
  //   icon: '&#xe603;',
  //   showList: ['id','userNum','allDeposit','allBalance','createTime'],
  //   api: 'manage/order/datInfo',
  //   // addUrl: 'Shuffling',
  // },
  // {
  //   name: 'roleList',
  //   text: '管理角色',
  //   icon: '&#xe602;',
  //   showList: ['id','name','type'],
  //   api: 'manage/getRole',
  //   addUrl: 'role',
  // },
  // {
  //   name: 'rechargeList',
  //   text: '提现记录',
  //   icon: '&#xe609;',
  //   showList: ['userId','type', 'moneyType','mType','cMoney','note','orderId','createTime'],
  //   api: 'manage/money/rechargeList',
  // },
  // {
  //   name: 'logList',
  //   text: '钱包变化',
  //   icon: '&#xe672;',
  //   showList: ['id','type', 'moneyType','note','sMoney','cMoney','eMoney','createTime'],
  //   api: 'manage/money/logList',
  // },
  // {
  //   name: 'feedbackList',
  //   text: '用户反馈',
  //   icon: '&#xe685;',
  //   showList: ['id','userId','userName','userPhone','content', 'softwareVer','hardwareVer','isRead','createTime'],
  //   api: 'manage/user/userFeedback',
  //   // addUrl: 'Shuffling',
  // },
  // {
  //   name: 'adminList',
  //   text: '管理列表',
  //   icon: '&#xe638;',
  //   showList: ['id','nickname','phone', 'email','status','last_login_time'],
  //   api: 'manage/userList',
  //   addUrl: 'admin',
  // },
  // {
  //   name: 'adList',
  //   text: '广告列表',
  //   icon: '&#xe64b;',
  //   showList: ['id','img','title','type','note','url','createTime'],
  //   api: 'manage/getAdAll',
  //   // addUrl: 'advert',
  // },
  // {
  //   name: 'personalInfo',
  //   text: '用户信息',
  // },
  // {
  //   name: 'Goods',
  //   text: '商品详情',
  // },
  // {
  //   name: 'Post',
  //   text: '文章详情',
  // },
  // {
  //   name: 'Shuffling',
  //   text: '轮播详情',
  // },
  // {
  //   name: 'Advert',
  //   text: '广告详情',
  // }
]