// subbar
export default {
  id:'ID',
  name: '名称',
  sn: 'SN',
  roadCount: '货道数量',
  address: '地址',
  online: '是否在线',
  doorOpened: '门是否打开',
  addressType: '地址类型',
  category: '设备型号',
  province: '省',
  city: '市',
  district: '区',
  createdAt: '创建时间',
  updateAt: '更新时间',
  updatedAt: '更新时间',
  supplyer: '补货员',
  mobile: '电话',
  deviceCount: '设备数',
  category: '类别',
  brand: '品牌',
  thumbnail: '图片',
  thumbnails: '图片',
  basicPrice: '价格',
  costPrice: '成本价',
  no: '编码',
  item: '商品',
  device: '设备',
  amount: '库存',
  price: '价格',
  status: '状态',
  fault: '是否故障',
  faultAt: '故障时间',
  username: '用户名',
  birthday: '生日',
  wxuserid: '微信ID',
  aliuserid: '支付宝ID',
  age: '年龄',
  firstBuyAt: '首次购买',
  lastBuyAt: '最后购买',
  buyCount: '购买次数',
  buyCountOf28Days: '28天购买次数',
  redeemTotal: '优惠券总数',
  redeemUsed: '优惠券使用数',
  road: '货道',
  payMoney: '支付金额',
  payType: '支付方式',
  payAt: '支付时间',
  user: '用户信息',
  deliverAt: '出货时间',
  image: '图片',
  video: '视频',
  totalOrder: '总订单数',
  alipayOrder: '支付宝订单数',
  wxpayOrder: '微信订单数',
  redeemOrder: '兑换码订单数',
  totalIncome: '总收入',
  name: '用户',
  pay_name: '付款人',
  gc: '打赏钻石数',
  create_time: '时间',
  account: '账户信息',
  rmb: '金额',
  fee: '打赏比例',
  start: '时间',
  sex: '性别',
  content: '内容',
  read: '阅读量',
  comment: '评论量',
  like: '点赞量',
  headimgurl: '头像',
  game_id:'游戏ID',
  // id: '用户ID',
  phone: '手机号',
  microblog_nickname: '被举报人',
  microblog_content: '举报内容',
  update_time: '财务处理时间',
  class_name: '操作类别',



  identityCard: '身份证',
  levelName: '等级名称',
  id:'ID',
  level:'等级',
  nickname:'昵称',
  nickName:'昵称',
  phone:'手机号',
  email: '邮箱',
  pswd: '密码',
  realName:'真实姓名',
  updateTime: '修改时间',
  createTime: '创建时间',
  levelDeposit: '所需金额',
  levelDiscount: '折扣比例',
  levelId: '等级',
  status: '状态',
  address: '地址',
  birthday: '生日',
  city: '城市',
  photo: '头像',
  province: '省',
  goodsClassName: '主分类名称',
  goodsClassModels: '子分类列表',
  goodsDetails: '商品详情',
  amount:'阅读数',
  articleName:'文章标题',
  aticleImg:'文章封面',
  authorName:'作者昵称',
  authorUserId:'作者ID',
  likes:'喜欢人数',
  brand:'品牌',
  brief:'简介',
  classId:'分类ID',
  classPid:'父分类ID',
  discount:'折扣',
  goodsName:'商品名称',
  goodsPhoto:'商品图片',
  price:'价格',
  sale:'销量',
  stock:'库存',
  cost: '成本价',
  img: '图片',
  title: '标题',
  note: '备注',
  type: '类型',
  detailsId:'链接ID',
  url: 'url',
  deposit: '存款',
  balance: '余额',
  original:'原价',
  payType:'支付方式',
  reduction:'优惠金额',
  userId:'用户ID',
  orderId:'订单ID',
  goodsList: '商品',
  complaint:'投诉内容',
  adminId:'处理人ID',
  userNum:'用户总数',
  allDeposit:'定金总数',
  allBalance:'总金额',
  roleName:'角色名称',
  roleType:'角色类型',
  moneyType:'付款类型',
  mType:'完成状态',
  cMoney:'变化金额',
  userName:'用户昵称',
  userPhone:'手机号',
  hardwareVer:'硬件版本',
  softwareVer:'软件版本',
  isRead:'状态',
  last_login_time: '上次登录时间',
  addressID: '发货信息',
  bankCardName: '户主名',
  identityCard: '身份证',
  bankName: '开户行',
  bankCardId: '银行卡号',
  bankAddress: '银行地址',
  elseOrderId: '快递单号',
  afford: '售价',
  sMoney: '变化前金额',
  eMoney: '变化后金额',
  cardName: '名称',
  cardMoney: '金额',
  cardDetails:'详情',
  cardNum:'数量',
  cardOutTime:'有效期',
  useCardNum:'领取数',
  endTime:'过期时间',
  top: '置顶等级',
  levelNum: '可领取次数',


  activity: '动作',
  sysCourseName: '标题',
  twoClass: '分类',
  price: '价格',
  courseCount: '子课程数',
  lecturer: '发布人',
  studentCount: '学生人数',
  imgUrl: '图片',
  skipId: '跳转id',
  company: '来源',
  courseClassName: '名称',
  ico: '图片',
  activityTitle: '活动标题',
  activityAddress: '活动地址',
  activityImg: '活动图片',
  activityMoney: '报名费用',
  activityNum: '最多参加人数',
  activityType: '状态',
  hasNum: '已参加人数',
  twoClassJpas: '二级分类',
  consultName: '标题',
  consultImg: '图片',
  num: '阅读数',
  commentNum: '评论数',
  authorId: '发帖人ID',
  credit: '学分',
  pid: '父级id'
}
